// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ZSjCc38ZkwBtYGD2axn3ewXmrgyJggg',
    appId: '1:878392926146:web:c22f39017086db73e1005b',
    messagingSenderId: '878392926146',
    projectId: 'cctv-hidroponik',
    authDomain: 'cctv-hidroponik.firebaseapp.com',
    databaseURL: 'https://cctv-hidroponik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cctv-hidroponik.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAioxXJbMLDZtdcllmOFDkO3b-p5xSyVZU',
    appId: '1:878392926146:android:24e37dc505f9f8c0e1005b',
    messagingSenderId: '878392926146',
    projectId: 'cctv-hidroponik',
    databaseURL: 'https://cctv-hidroponik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cctv-hidroponik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCofRkcdkVvrJ0ffCWULOvvbQqtlqjGGkU',
    appId: '1:878392926146:ios:642e25bf8ccc9c6fe1005b',
    messagingSenderId: '878392926146',
    projectId: 'cctv-hidroponik',
    databaseURL: 'https://cctv-hidroponik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cctv-hidroponik.appspot.com',
    iosBundleId: 'com.example.cctvIot',
  );
}
